### ISSUE TITLE
ng-idle support with angular2

### ISSUE THREAD

**Issue by david-gang** [HackedByChinese/ng-idle#119]
Hi,

This module is really great and it would be nice to have it supported with angular 2.

Thanks a lot,
David

**Comment by HackedByChinese** [comment]
I will be writing an Angular 2 version. However, I think it will likely be under a different project (i.e. ng-idle2) because of significant differences between the two frameworks and the divergent life cycles between Angular 1.x and Angular 2.

If anyone has any feedback or suggestions on how to manage the module for both versions of Angular, I'm all ears.

**Comment by mbcooper** [comment]
Hi!

Any progress or notions on how you will table this?

**Comment by HackedByChinese** [comment]
Yes, I started investigating an Angular 2 version. It is a completely separate repo, and I'm separating all the major features as separate modules so people can pick what they need. 

The permanent homes are/will be:

https://github.com/HackedByChinese/ng2-keepalive
https://github.com/HackedByChinese/ng2-idle

I don't have much to show at the moment, but you can watch either of those repos to look for updates.

**Comment by HackedByChinese** [comment]
I'm going to close this ticket. Checkout ng2-idle for more info (currently alpha.1 release; I'll have more features shortly).

**Comment by wiworowa** [comment]
Hi, I am try to use ng-idle on net core but for some reason it said that it can noy load http://localhost:3000/js/@ng-idle/keepalive
