### ISSUE TITLE
Line 290 giving error in IE 11: if (event.type === 'mousemove' && event.originalEvent.movementX === 0 && event.originalEvent.movementY === 0) {

### ISSUE THREAD

**Issue by optimacycorp** [HackedByChinese/ng-idle#121]
event.originalEvent.movementX is undefined when the application boots up.

**Comment by david-gang** [comment]
This happens me also on chrome.
This is due to the commit:
https://github.com/HackedByChinese/ng-idle/commit/d2e8c245158a1c899a83214fb57ac93fef26d072#diff-0b7345e280001be45821e57dbf49a37c

Now the question is why are we downloading the master branch :-)

Quite easy. The last release does not work with browserify. Just the master branch.
So we are quite stuck :-).

The fix would be really easy.

event.type === 'mousemove' && && event.originalEvent &&event.originalEvent.movementX === 0 && event.originalEvent.movementY === 0


I don't know if this intended, but let's hear what @HackedByChinese is thinking about this.

Another option would be to make a release with just the fix of browserify.

**Comment by dadoadk** [comment]
Is this still an issue? I ran the demo in IE11 and it didn't work.

**Comment by HackedByChinese** [comment]
The fix for this will be released shortly.
