### ISSUE TITLE
multiple tabs with no timeout

### ISSUE THREAD

**Issue by phazei** [HackedByChinese/ng-idle#158]
There doesn't seem to be a way to handle multiple tabs with no timeout.

Our use case has a idle time, but when that's hit, the modal that comes up asks if they want to log out and has a timeout period.  With ng-idle, there's no way to request if they want to logout with a timeout period because the moment you do anything, the timeout is reset and it's checking the idle again.

So we disabled the timeout, and are just using the IdleStart.  When that's triggered, we don't want to have watch continue going because it needs to be paused and we don't want IdleStart triggered again while the modal is up, so we need to call unwatch, but then we can't see if another tab is !isExpired, because it's unset on unwatch.

Would be nice to be able to set the state as invalid until it could be set not to.

**Comment by HackedByChinese** [comment]
I'm having a little trouble following along, because I keep trying to connect this to an issue with multiple tabs.

What it sounds like you're asking is for an option to prevent user activity from resuming once they go idle. In other words, once I go idle, I have to click a button or something manual like that in order to extend their session.

If that's correct, I have good news. This functionality is called *autoResume*. The config you seem to be describing would be `.autoResume('notIdle')`. See the [wiki](https://github.com/HackedByChinese/ng-idle/wiki/Idle-and-Idleprovider#idleprovider) for more info.
