### ISSUE TITLE
Improve setup of dev working copy

### ISSUE THREAD

**Issue by grbsk** [HackedByChinese/ng-idle#16]
Make it work from a single, simple `npm install` command so contributors have less farting around to do.

**Comment by cyril-blanco** [comment]
Hello!

This patch is a bad idea because it makes bower mandatory when installing with npm.

I'm using npm as a dependency manager (with browserify), no bower at all. Installing your module as a npm package triggers the postinstall script, which invokes bower. As far as I can tell, the bower_components files are only used for tests (in karma.conf.js), not for runtime.

I am trying to find a way to avoid this "postinstall" in package.json while still be able to run tests when using as a node module (installing angular via npm dev-deps could solve this, but the tests won't run anymore because they look for files in bower_components)
