### ISSUE TITLE
Not working with iFrames

### ISSUE THREAD

**Issue by linux-nerd** [HackedByChinese/ng-idle#162]
Hi,

I have an application where iFrames are used. Even if the user is active on the iFrame, the ng Idle times out. What is the fix for this?

Thanks

**Comment by anuja-joshi** [comment]
@linux-nerd Events fired on iFrame does not get propagated to parent document and as `ng-idle` is looking for certain events  (`mousemove keydown DOMMouseScroll mousewheel mousedown`  by default) on parent document, the `interrupt` is not considered and hence `ng-idle` gets times out.
What you can do is, manually trigger events on parent document when events on iFrame occurs.
Like, add script in iFrame to execute following:
```
document.addEventListener('click', function(){ parent.$('body').trigger('click') });
```
This will trigger 'click' event on parent when 'click' is triggered on iFrame. Similarly, you will have to trigger parent event for all the DOM events you are watching for.
PS - You can execute such script in iFrame only if you follow [Same Origin Policy](http://javascript.info/tutorial/same-origin-security-policy)

**Comment by HackedByChinese** [comment]
@anuja-joshi's recommendation makes the most sense. If you have a single IFrame that's always present in your app, it's less complicated. However, detecting when IFrames are added and removed (which is important, because [some browsers](http://stackoverflow.com/questions/8407946/is-it-possible-to-use-iframes-in-ie-without-memory-leaks) have a memory leak if you don't clean up when frames are removed) is quite a bit more complicated. 

It's best to break this out into your own directive when adding IFrames that adds and removes event listeners to the frame that trigger `Idle.interrupt()`.
