### ISSUE TITLE
What is the purpose of id

### ISSUE THREAD

**Issue by linux-nerd** [HackedByChinese/ng-idle#165]
I was going through the source code, and I found 
`if (val.id === id) return;`

I am curious, what is the need to check the id, or to put it in a different way, why do we need to store id along with timeout in the local storage?

Reason of my curiosity - 
I have two different application and I need to implement auto logout on both the application. One is based on angular and the other on jQuery. For angular app I am using ngIdle and for jquery I will  be using some jquery plugin. 

The issues which I will face is 

1. The way timeout is stored in the local storage and the key (2016-07-22T05:31:11.871Z)
2. The key of the local storage (ngIdle.expiry)

Is there a way to change the local storage key and time format (say in milliseconds) ?

**Comment by HackedByChinese** [comment]
Each ng-idle instance records a timestamp and uses that as the `id`. The purpose of `id` is to squelch localStorage update events. Otherwise, an instance will write the new update time and receive an event in localStorage from itself and trigger an infinite loop. If the localStorage update event is from another ng-idle instance (say, another tab to the same app), the `id` will be different and processed normally.

The only scenario where there is no support is if you have multiple but completely independent Angular apps that use ng-idle and are hosted in the same exact domain, and you want them to have independent idle detection as well. In that case, we would want to be able to add a configurable prefix to the localStorage key name where the idle information is stored. If more people request it, I can add it.

**Comment by linux-nerd** [comment]
The scenario I have to deal with is there are two applications one in angular and the other in jQuery. And I am using ngIdle for angular application and will use jquery-idleTimeout for jQuery application. And I want them to logout simultaneously when both are idle.

The time format for jquery-idleTimeout is in milliseconds which is different from ngIdle. Is there a way how can I deal with this?

**Comment by nijeeshvayalassery** [comment]
@HackedByChinese , Is there any way to configure sessionstorage instead of localstorage. If we use same application in multiple tabs, both instances use the same localstorage. Is there any work around for this issue. Thanks in advance.
