### ISSUE TITLE
ng-idle doesn't fire when tab is not focused

### ISSUE THREAD

**Issue by altryne** [HackedByChinese/ng-idle#41]
I'm trying to implement ng-idle instead of our homebacked solution, to logout users after 15 minutes of inactivity, but to send http pings if they are active.
It seems that it kinda works, as I send the logout command on $scope.$idleEnd
but it only happens when I'm active on the tab. It doesn't happen in background, for instance if I moved to another tab and waited there, the event won't seem to fire unless I come back to the tab.
Is this intended behavior? And if this is, how can I make ng-idle disconnect the user in background?

**Comment by HackedByChinese** [comment]
Some browsers may suspend the process for a tab when it is not active. For example, most mobile browsers do this to save battery life and improve performance. When a tab is suspended, the keepalive and timeout will not, cannot work.

However, I implemented change #10 so that when you come back to the tab and do something, it will do a check to see if you _should_ have timed out, and if so, issue the timeout event as you would expect. However, that may not happen until some arbitrary time in the future when the user activates the tab again.

To keep security tight, you should be setting an expiry on your authentication tokens or cookies and not rely only on `ng-idle`. Unfortunately, I can't do anything about suspended processes.

For browsers that do _not_ suspend inactive tabs, you shouldn't be having any problems.

**Comment by altryne** [comment]
:+1: thanx for the fast response.
I think I got confused and was waiting for the wrong event, and then when I came back, the idle stopped, I sent a ping to the server, that was invalidated already and so that's why I was logged out.

**Comment by colepanike** [comment]
Quick question, I can see the following case occurring.

Assume the following settings:
- 14 min IdleWarn, 1 min timeout for a total 15 min inactivity
- 10 min keepalive
- 15 minute server session

Scenario:
- User pulls up the app and goes about their business, keeping the timeout pushed off
- After 7 minutes the user moves to another browser tab
- They're gone for about 10 minutes, 3 minutes into which a keepalive should have been issued but the tab has been suspended
- User returns, no timeout is triggered (this is correct) but the server session really did expire, they just don't know.

Does the directive handle such a case? If so, how? I hope it would simply fire the IdleTimeout?
