### ISSUE TITLE
Karma/Jasmine test Failing

### ISSUE THREAD

**Issue by bhaskarGyan** [HackedByChinese/ng-idle#43]
Hi 
I am using ng-idle in my project and everything worked great until i checked my unit tests.
All my test are failing since after adding 'ngIdle' in my app dependency my app is failing to load during Unit test.I am getting below Error

39m	Error: [$injector:modulerr] Failed to instantiate module test due to:
	TypeError: undefined is not a function
	    at F:/Projects/abc/client/app/Features/Pay/PayBeneficiary/PayBeneficiary.js:9:501
	    at Object.invoke (F:/Projects/abc/client/bower_components/angular/angular.js:3966:17)
	    at F:/Projects/abc/client/bower_components/angular/angular.js:3885:37
	    at forEach (F:/Projects/abc/client/bower_components/angular/angular.js:325:18)
	    at loadModules (F:/Projects/abc/client/bower_components/angular/angular.js:3872:5)
	    at Object.createInjector [as injector] (F:/Projects//abc/client/bower_components/angular/angular.js:3812:11)
	    at Object.workFn (F:/Projects/abc/client/bower_components/angular-mocks/angular-mocks.js:2339:52)

My app.js

'use strict';

angular.module('test', [
  'ngIdle',
  'ngCookies',
  'ngResource',
  'ngSanitize',
  'ui.router',
  'dateRangePicker',
  'ui.select',
  'ngIdle'
])
  .config(function ($idleProvider, $keepaliveProvider) {
     $idleProvider.idle(5); // in seconds
    $idleProvider.timeout(60); // in seconds
    $keepaliveProvider.interval(20); // in seconds
 })
   .run(function($idle){
             $idle.watch();
   });

and in my Karma config 

 files: [
      'client/bower_components/jquery/dist/jquery.js',
      'client/bower_components/angular/angular.js',
      'client/bower_components/angular-date-range-picker/build/angular-date-range-picker.js',
      'client/bower_components/angular-mocks/angular-mocks.js',
      'client/bower_components/angular-resource/angular-resource.js',
      'client/bower_components/angular-cookies/angular-cookies.js',
      'client/bower_components/angular-sanitize/angular-sanitize.js',
      'client/bower_components/lodash/dist/lodash.compat.js',
      'client/bower_components/angular-ui-router/release/angular-ui-router.js',
      'client/bower_components/foundation/js/foundation.js',
      'client/bower_components/foundation/js/foundation/foundation.reveal.js',
      'node_modules/karma-jasmine-jquery/lib/jasmine-jquery.js',
      'client/bower_components/angular-bindonce/bindonce.js',
      'client/bower_components/moment/moment.js',
      'client/bower_components/moment-range/lib/moment-range.js',
      'client/bower_components/ng-idle/angular-idle.min.js',
      'client/app/app.js',
      'client/app/*.js',
      'client/components/*.js',
      'client/app/*.html',
      'client/components/*.html',    
    ],
If i remove ngIdle from app dependency all my test are passing. 
**am I missing something?**
 I even tried the ng-idle-test but it is throwing  Error: [$injector:unpr] Unknown provider: $$qProvider <- $$q <- $interval <- $idle Error.

**I am using angular 1.25 and jasmine 2.0**

**Comment by HackedByChinese** [comment]
First, let's talk about the second issue, not being able to get `ng-idle-test` to run. Let's imagine this scenario (I just ran through it, so this is an actual example, not theoretical):

I clone `ng-idle-test` and run `npm install`. It pulls down Node packages and then gets to the `bower install` part and walks the dependency tree. It sees that the project's `bower.json` as a bunch of Angular modules listed with the version `~1.3` (which means "any version starting with 1.3"). It looks at `ng-idle` 0.3.5 and sees that it requires Angular ~1.2. Everything else needs ~1.3. It'll stop and ask you what you want to do, install the latest 1.2 or the latest 1.3? Naturally, since you know your other project is 1.2, you might say to use 1.2. It _does_ pull down Angular 1.2, but unfortunately, all the ancillary Angular modules we listed as dependencies are still the 1.3 versions of those Angular modules (cookies, animate, resource, mock, etc.). Bower has no way of knowing that all those other Angular modules should be downgraded to a version that is compatible with Angular 1.2.x. Anyways, you're unaware that this happened, so you run `grunt test` and see that it failed with the line `Unknown provider: $$qProvider <- $$q <- $interval <- $idle`. As I've been building up to, this error is because you have some other module loaded that is incompatible with either Angular or another Angular module. In this case, I think it's because we tried to use Angular Animate 1.3 with Angular 1.2. The fix, in this case, is to change the required version of all those Angular modules to ~1.2 (the easiest way is to probably just delete `bower_components` and edit `bower.json` and replace 1.3 with 1.2, then run `bower install` again). Once it's fixed, run `grunt test` and you'll see it completes successfully.

As to your main question, I don't know if the trouble you had in `ng-idle-test` is related to the issue you're having in your project. You can start by looking at your `bower.json` file to see if you have any obvious version mismatches like we discussed above (you can attach the relevant lines in your `bower.json` file here, if you are really lost). Another thing to do is look at all your dependencies and make sure they don't require a different version of a component than you already have (ng-idle works with 1.2 and 1.3, BTW, so it shouldn't be that module). You can also try linking me to (or privately sending me) your test and this PayBeneficiary.js, or your repo itself so I can look for issues.
