### ISSUE TITLE
ng-countdown not causing a digest when updating countdown value

### ISSUE THREAD

**Issue by xxJimxx** [HackedByChinese/ng-idle#46]
I'm only seeing the IdleWarn event fired when idle expires and then when timeout expires.  My impression was that this would fire every second during the timeout period?  

I attempted to implement in plunker to give example code but doesn't seem to work at all there.  I think it is a fairly good representation of what I am doing though.  http://plnkr.co/edit/Tv1rmD?p=info  

note: the header comment still references this as  "* @version v0.3.5"

**Comment by HackedByChinese** [comment]
Version 1.0.0 hasn't been released yet. I still have an issue or two to close and then I'll release it.

**Comment by xxJimxx** [comment]
I'm a github noob, I found the master version.  Thx

**Comment by HackedByChinese** [comment]
I did fork your plunk though. There were a few errors:

1. `EventsCtrl` references `$modal` but wasn't specifying it as a dependency.
2. Under Index.html, your warning modal used the directive `ng-idle-countdown`. In 1.0.0, this directive drops the ng prefix and is just called `idle-countdown`.
3. In that same modal template, you were using a static value of 5 for `value`, rather than `countdown`.

However, even after those changes, it still wasn't updating the dialog. It's not doing that for me in any of my other samples. I modified the `idle-countdown` directive in the `angular-idle.js` file you included in your plunk and added a `$scope.$apply` to force Angular to perform a digest. Then it worked.

We shouldn't have to do that, but maybe I'm mistaken. I'll look into it.

My fork: http://plnkr.co/edit/LuNBwg6s9QYnJ0OgBM7c?p=preview
