### ISSUE TITLE
Scroll should be a default interrupt event

### ISSUE THREAD

**Issue by AndersWinther-Dahl** [HackedByChinese/ng-idle#48]
Hi,
Thanks for this great module!

I'm wondering if it's possible to detect if a user scrolls by clicking and dragging on the scrollbars?
When testing in Chrome, it doesn't.

Scrolling with mousewheel or touchpad, stops the Idle.

Best regards
Anders

**Comment by HackedByChinese** [comment]
Hmm, it seems I missed the `scroll` event in the default events it watches. It probably makes sense to add this to the default list.

While you're waiting for an official release, you can add this using the current release by configuring it in your module's `config`:

    angular.module('myApp', 'ngIdle')
           .config(function(IdleProvider) {
               IdleProvider.activeOn('mousemove keydown DOMMouseScroll mousewheel mousedown touchstart touchmove scroll');
           });

**Comment by AndersWinther-Dahl** [comment]
Thanks!

**Comment by AndersWinther-Dahl** [comment]
Hi Mike,
I'm using version 1.0.0, so I guess it should be the .interrupts. I already used it since I wanted to disable interrupt on 'mousemove'. Now I have this in my .config:
IdleProvider.interrupt('keydown DOMMouseScroll mousewheel mousedown touchstart touchmove scroll');
I tested again, but still no interrupt on dragging scrollbar. I also noticed that scroll by touchpad didn't do it.

Can you help me?

Best regards
Anders

**Comment by HackedByChinese** [comment]
1.0.0 is not actually released yet. You pulled the file from the development branch. Perhaps one of the changes I made in anther commit messed something up. If you can try this on the last official release (see the releases tab on Github or use bower) and see if it works any better. =

**Comment by AndersWinther-Dahl** [comment]
Thank you for your feedback.
I now tried it in 0.3.5 release. Still no luck I'm afraid. The countdown starts but only gets interrupted by mouse click or key down events.
In my .config I have:
$idleProvider.activeOn('keydown DOMMouseScroll mousewheel mousedown touchstart touchmove scroll');

My controller is limited to a div in the bottom of the page, since this will be an add-on for several existing solutions, where I'm trying not to change too much. Could it be the explanation why the scroll event isn't fired inside my idle-controllers scope?
I found a JSFiddle, where the scroll event seems to get detected:
http://jsfiddle.net/ADukg/4831/
But I noticed that it only shows when I scroll the list <ul>, and not if I resize the window and get another scrollbar around the list. When I scroll that one, nothing happens in the log.

**Comment by HackedByChinese** [comment]
What version of AngularJS are you using? The fiddle shows 1.0.1, which this module is not compatible with.

I do attach the event to document.body, so it's possible that scroll events on specific elements, where you are clicking and/or dragging the scrollbar around rather than using touch or mouse wheel, might not be picked up.

You could create a directive based off the one in your fiddle that in the `scroll` event handler, calls `$idle.watch()` to manually reset the state. You can then attach this directive to fill these little gaps.

**Comment by AndersWinther-Dahl** [comment]
The fiddle wasn't my own creation. I just found it via Stackoverflow.

I will look into the solution of calling $idle.watch() manually.

Thanks!

**Comment by xxJimxx** [comment]
Testing this in my environment; AngularJS v1.3.8, UI-Bootstrap 0.12, ngIdle v0.3.5 and Chrome v34.x. With my angular controller assigned to the document body.

As soon as the UI modal appears the scroll bar disappears, I move my mouse and it dismisses the modal.  

I am able to duplicate when actively scrolling the from the chrome scroll bar I will still receive the warning.  I added the statement to the config,  $idleProvider.activeOn('mousemove keydown DOMMouseScroll mousewheel mousedown touchstart touchmove scroll'); with no change in behavior.

I think this would be expected behavior because the browser scroll bar is outside of the angular scope.  

My idle duration will be 13 minutes and warn for 2 minutes in production.  I can't imagine someone scrolling for 13 minutes without releasing and moving the mouse over the document. I understand your environment is a bit different but confirming that the browser scroll does not fire an event in the angular scope in my test either.

**Comment by HackedByChinese** [comment]
The problem might be because I’m observing the scroll event on the document body (with the rest of the interrupt events), rather than on the window. I might have to set an explicit observation for scroll on $window (and probably remove it from the interrupt events, as it seems it has little effect).

Thanks for your feedback on this.=
