### ISSUE TITLE
Is it possible to start idle after last xhr request

### ISSUE THREAD

**Issue by iyel** [HackedByChinese/ng-idle#51]
* My session will expire after 2 hours of http inactivity is it possible to listen to this? 
* And can I interrupt it on button click inside modal?

**Comment by HackedByChinese** [comment]
- The module does not consider `$http` activity to determine idleness. The goal of this module is to look for _user input/interaction_.
- Yes, you can manually interrupt by injecting `$idle` (or `Idle` in the upcoming v1.0.0 release) and calling `watch()`.

**Comment by iyel** [comment]
I meant that my session will expire if user didn't do anything that will trigger API calls. Did I understand correctly that ```Keepalive``` service can help me with this?

**Comment by HackedByChinese** [comment]
Oh, sorry. Yes. By default, the idle service will use keepalive. keepalive will ping every 10 minutes (by default, configurable) while the user is active. It will stop pinging once the user enters the idle state. When the user returns to the active state after going idle, keepalive will immediately ping.

All you need to do is configure `$keepaliveProvider.http()` (or `KeepaliveProvider.http()` in v1.0.0) and it'll start sending HTTP requests for you using the options you specified. This works great for cookie-based session tokens because (in most cases) you just send a request to an HTTP endpoint and the browser will automatically include the session cookie for you. If that endpoint updates the session cookie and sends it back, the browser will take care of that for you, too. 

However, if you need more control over sending and processing keepalive requests, you can leave `http()` option unset, listen for the `$keepalive` event (or `KeepAlive` in v1.0.0) and handle it yourself.

**Comment by iyel** [comment]
Thanks, now it is clear. When are you going to release v1.0.0?
