### ISSUE TITLE
Two Browser Tabs with ng-idle use same LocalStorage entry, causing problems

### ISSUE THREAD

**Issue by ertanden** [HackedByChinese/ng-idle#72]
I'm opening my web app on the browser tabs at the same time (same browser). Looks like the LocalStorage is the same for both browsers so they interact with each other, making strange things and errors appear in console for ng-idle.

Somehow we need to distinguish the two tabs from each other...

Think about two different web-apps both using ng-idle. Strange things may happen.

**Comment by ertanden** [comment]
Specific test steps.

1. Open http://hackedbychinese.github.io/ng-idle/ in two browser tabs
2. Start the demo on both tabs
3. Immediately stop the demo on the second tab
4. Warning dialog appears on first tab, but no mouse activity can prevent the expiry!!!

Errors on console:

Uncaught TypeError: Cannot read property 'id' of null
Uncaught TypeError: Cannot read property 'time' of null

**Comment by yashikagarg13** [comment]
Any updates on this issue

**Comment by HackedByChinese** [comment]
The purpose of using `localStorage` is so that the browser tabs _do_ interact with each other. `localStorage` is persistent across pages that follow same-origin, so the idea is that if you have the same application that pops open multiple windows or tabs, they can coordinate idleness between each other (if you're busy in tab 2, we don't want tab 1 to time out, etc.) using `localStorage`.

Two different web applications cannot read/write into each other's `localStorage`; they each get their own. So, if these two different web applications each use `ng-idle`, they should be OK and not interfere with each other. There is a possibility that if you use two different web applications _in the same site_ and you need to have different idle session checking for each, this could present an issue. However, I don't know how realistic or prevalent that scenario is; I'll leave it to community feedback to decide.

That being said, the errors you are seeing were addressed in #76 (which now that I think about it, I may have forgotten to put out a new patch version with this fix).

**Comment by ertanden** [comment]
Did you run over the test steps that I wrote and see the problem for yourself? I'm not talking about the console errors. 

Basically, the two tabs are interfering with each other and then no mouse activity can prevent an expiry!

**Comment by HackedByChinese** [comment]
Sorry if I wasn't clear. The issue you were experiencing was a side effect of the bug in #76, which is fixed and available in v1.1.0.

The demo page uses the latest in master, so now it's using v1.1.0. If you do a hard reload on the demo page and run your test steps, you should see it's working as expected now. I just tried it in Chrome a few times and it looks good.

**Comment by ertanden** [comment]
Great. It looks fixed. You can close this issue then... Thank you very much.

**Comment by BhagyashriJ** [comment]
Its not working. Its having same entry in local storage even if its opened in different tabs and I have logged in as different users.

**Comment by greatsayan** [comment]
+1
is not fixed... any updates for that issue?
