### ISSUE TITLE
ng-idle is not working in IE9 and IE10, Suppose if you leave mouse pointer on the page it is not considering user is inactive.

### ISSUE THREAD

**Issue by LaxmiNarasimha530** [HackedByChinese/ng-idle#88]
ng-idle is not working in IE9 and IE10, Suppose if you leave mouse pointer on the page it is not considering user is inactive. When you keep mouse pointer outside page it is working. 

Please provide solution for this.

**Comment by HackedByChinese** [comment]
At one point after the v1.0.0 release, there was a bug because of how IE handles localstorage (which is used to facilitate timeouts between multiple tabs open to the same application). That was fixed, so some more recent change must have caused a regression.

I do not have access to an IE9 or IE10 machine at the moment, so I'll need help from people where IE9-10 is important to them.

**Comment by Nirmalendu4u** [comment]
It seems the issue is with the mousemove event, the quick fix for it can be the removal of mousemove event for the IE browser. Write a conditional statement using useragent and use interrupt() method of ng-idle to configure events.
